### ISSUE TITLE
Populate TBox from files

### ISSUE THREAD

**Issue by alex-mitrevski** [b-it-bots/mas_knowledge_base#19]
Just as for assertions, it could be useful to have the possibility to add new classes and object properties to the ontology using a (possibly YAML-based) configuration file.

This is related to https://github.com/b-it-bots/mas_knowledge_base/issues/2 and https://github.com/b-it-bots/mas_knowledge_base/pull/17

**Comment by Sushant-Chavan** [comment]
@alex-mitrevski, A few questions regarding the TBox definition removal APIs:

1. When a class is removed, should we remove all its subclasses as well?
2. When a class is removed, should we remove all the properties which have their domain/range as the class to be deleted?
3. When a class/property is removed, should we remove all the assertions associated with the class/property?

**Comment by alex-mitrevski** [comment]
2 and 3 should definitely be done I think. I'm not sure about 1, but my gut feeling is we shouldn't do it (worst case - if `Object` is removed, all classes and properties from the ontology will be removed).

**Comment by Sushant-Chavan** [comment]
But, if we don't remove the sub-classes, the immediate children of the class that was removed will be treated as the top-level classes (i.e. at the same level as Object) right? Is this desired?

**Comment by alex-mitrevski** [comment]
I think whoever is deleting the classes should simply be aware of this behaviour, but I think it would be desired. I also don't think it would make sense to clear out the ontology just because you want to delete the top-level class, for example.

**Comment by Sushant-Chavan** [comment]
Ok, So I will proceed with implementing just the points 2 and 3 mentioned above.

**Comment by Sushant-Chavan** [comment]
@alex-mitrevski, I was thinking we could use the following format for the YAML file with class and property definitions. What do you think?

```
class_definitions:
    class_name1: [] # Interpreted as top level class
    class_name2: [ParentClass1]
    class_name3: [ParentClass1, ParentClass2] # Multiple parent classes
property_definitions:
    property_name1:
        domain: [domain_ns (or None), domain_name]
        range: [range_ns (or None), range_name]
        type: 'PropertyType' # or None
    property_name2:
        domain: [domain_ns (or None), domain_name]
        range: [range_ns (or None), range_name]
        type: 'PropertyType' # or None
```
